version: 2
jobs:
  build:
    docker:
        - image: eoshep/build-essentials:bionic
    steps:
      - checkout
      - run:
          name: dependencies_install
          command:  apt-get update && apt-get install -y software-properties-common wget build-essential

      - run:
          name: cmake_install
          command: apt-get install -y cmake
    
      - run:
          name: sdl_install
          command: apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev

      - run:
          name: build
          command: cmake CMakeLists.txt && SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy make all